server:
    port: 8089
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/weixin?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
      username: root
      password: chen
#打印sql日志
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


#代理设置
proxy: 
    enabled: false
    host: 192.168.18.233
    port: 8888

#REST超时配置
rest: 
    ReadTimeout: 35000
    ConnectTimeout: 5000
#测试微信支付
tenPay:
  url: https://api.mch.weixin.qq.com/pay/unifiedorder
  queryUrl: https://api.mch.weixin.qq.com/pay/orderquery
  appid: wxae1cf680e4713658
  appsecret: 369bb0a86753b7920a70d42a028009d8

#正式：
#appid: wx9ee2a0be4550fc82
#appsecret: 53959c2bb645222771d037786fedc2fb
